version: "3.9"
services:
  red5:
    image: red5
    container_name: red5
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./files:/usr/local/red5-setup/files
      - ./scripts:/usr/local/red5-setup/scripts
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    environment:
      - RED5_VERSION=10.4.0
